---
config:
  flowchart:
    curve: monotoneY
  theme: base
  themeVariables:
    clusterBkg: '#ffffff'
    edgeLabelBackground: '#ffffff'
    lineColor: '#000000'
    primaryBorderColor: '#000000'
    primaryColor: '#f0f0f0'
    primaryTextColor: '#000000'
---

flowchart TB
  subgraph main[" "]
    direction TB


    transferOwnership["Change post<br />ownership<sup>1</sup>"]
    transferOwnership --> transferOwnershipTemplate
    transferOwnershipTemplate["#quot;<b>Post ownership has<br />been transferred</b>#quot;<br />template"]
    transferOwnershipTemplate --> review
    review["Review flag"]
    review --> overviewWorkflow
    overviewWorkflow[["#quot;<b>Content deletion<br />handling overview</b>#quot;"]]
  end
