# See:
# https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

contact_links:
  - name: Learn about using this project
    url: https://github.com/arduino/forum-assets#readme
    about: Detailed usage documentation is available here.
  - name: General discussion and assistance
    url: https://forum.arduino.cc/
    about: Discussion of the project or requests for assistance are welcome on the Arduino Forum.
  - name: Issue report guide
    url: https://github.com/arduino/forum-assets/blob/main/docs/contributor-guide/issues.md#issue-report-guide
    about: Learn about submitting issue reports to this repository.
  - name: Contributor guide
    url: https://github.com/arduino/forum-assets/blob/main/docs/CONTRIBUTING.md#contributor-guide
    about: Learn about contributing to this project.
