name: Check ToC

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-toc.yml"
      - "moderator-instructions/moderator-instructions.md"
  pull_request:
    paths:
      - ".github/workflows/check-toc.yml"
      - "moderator-instructions/moderator-instructions.md"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    name: ${{ matrix.file.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        file:
          - name: moderator-instructions/moderator-instructions.md
            maxdepth: 4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install markdown-toc
        run: sudo npm install --global markdown-toc

      - name: Rebuild ToC
        run: |
          markdown-toc \
            --bullets=- \
            --maxdepth=${{ matrix.file.maxdepth }} \
            -i \
            "${{ github.workspace }}/${{ matrix.file.name }}"

      - name: Check ToC
        run: git diff --color --exit-code
